version: '3.7'
services:
  node:
    hostname: 'task-1'
    image: 'task-1:node'
    container_name: 'node'
    networks:
      - test-network
    restart: always
    build:
      context: . # context를 .로 해주어야 Dockerfile에서 경로를 ../ 바깥으로 나갈 수 있음
      dockerfile: Docker/node.Dockerfile
    env_file: .env
    depends_on:
      - DB
  DB:
    hostname: 'task-1'
    image: 'mongo:latest'
    container_name: 'mongoDB'
    networks:
      - test-network
    restart: always
    volumes:
      - './db:/data/db'

networks:
  test-network:
